name: CD

on:
  push:
    branches: [ develop ]
    paths-ignore: 
    - .github

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
  publish-storage-filesystem:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
      # Filepath of the project to be packaged, relative to root of repository
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        PROJECT_FILE_PATH: ./Glasswall.Common.Storage.FileSystem/Glasswall.Common.Storage.FileSystem.csproj
        
  publish-storage:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
      # Filepath of the project to be packaged, relative to root of repository
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        PROJECT_FILE_PATH: ./Glasswall.Common.Storage/Glasswall.Common.Storage.csproj
        
  publish-security:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
      # Filepath of the project to be packaged, relative to root of repository
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        PROJECT_FILE_PATH: ./Glasswall.Common.Security/Glasswall.Common.Security.csproj
        
        
  publish-test-common:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
      # Filepath of the project to be packaged, relative to root of repository
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        PROJECT_FILE_PATH: ./Glasswall.Common.Test.NUnit/Glasswall.Common.Test.NUnit.csproj
